math = (10 + 20)
math2 = (100 * 200)
math3 = (2000 / 100)
math4 = (30 - 20)
math5 = (5 + 2)
math6 = (1121 - 0)
Name = ("alex")
age = (12)
country = ("georgia")
city = ("tbilisi")
siblings = (2)
brother = ("misho")
sister = ("qeti")
father = ("davit")
mother = ("sofia")
print (math)
print (math2)
print (math3)
print (math4)
print (math5)
print (math6)
print (Name)
print (age)
print (country)
print (city)
print (siblings)
print (brother)
print (sister)
print (father)
print (mother)